CREATE TABLE public.patients
(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    PHONE TEXT NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    ADDRESS TEXT NOT NULL,
    GENDER TEXT NOT NULL,
    DNI TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);
